FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive


RUN apt-get update && apt-get install -y \
    make \
    wget \
    unzip \
    bzip2 \
    xz-utils \
    cppcheck \
    clang-format \
    git \
    libncurses5 \
    && apt-get clean && rm -rf /var/lib/apt/lists/*


WORKDIR /opt
RUN wget https://software-dl.ti.com/msp430/msp430_public_sw/mcu/msp430/MSPGCC/9_3_1_2/export/msp430-gcc-9.3.1.11_linux64.tar.bz2 \
    && tar -xjf msp430-gcc-9.3.1.11_linux64.tar.bz2 \
    && rm msp430-gcc-9.3.1.11_linux64.tar.bz2


RUN wget https://software-dl.ti.com/msp430/msp430_public_sw/mcu/msp430/MSPGCC/9_3_1_2/export/msp430-gcc-support-files-1.212.zip \
    && unzip msp430-gcc-support-files-1.212.zip -d msp430-gcc-support \
    && rm msp430-gcc-support-files-1.212.zip

RUN useradd -rm -d /home/ubuntu -s /bin/bash -g root -G sudo -u 1001 ubuntu

USER ubuntu

ENV PATH="/opt/msp430-gcc-9.3.1.11_linux64/bin:${PATH}"

WORKDIR /workspace